# file AUTO GENERATED by make_metadata.py, do NOT edit
import sys
# Remove current dir from sys.path, otherwise setuptools will peek up our
# module instead of system's.
sys.path.pop(0)
from setuptools import setup
sys.path.append("..")
import sdist_upip

setup(name='microhomie-node-bme280',
      version='0.1.1',
      description=u'BME280 node for the Homie MicroPython framework.',
      long_description=open(u'README.rst').read(),
      url='https://github.com/microhomie/microhomie-nodes',
      author=u'Fabian Gro\xdfe',
      author_email=u'fabian-grosse@t-online.de',
      maintainer='Microhomie Developers',
      maintainer_email='contact@microhomie.com',
      license='MIT',
      cmdclass={'sdist': sdist_upip.sdist},
      packages=['homie.node'],
      install_requires=['microhomie'])
